## Tensor Indexing

In [1]:
import torch

device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [3]:
batch_size = 10
features = 25

x = torch.rand((batch_size, features))
x.shape

torch.Size([10, 25])

In [4]:
x[0]  # x[0, :]

tensor([0.0651, 0.4096, 0.8372, 0.9364, 0.1613, 0.1827, 0.2652, 0.6326, 0.4341,
        0.6631, 0.2993, 0.3762, 0.0593, 0.4363, 0.1895, 0.5547, 0.9052, 0.5546,
        0.9358, 0.1449, 0.2467, 0.8290, 0.8592, 0.9208, 0.8471])

In [5]:
x[0].shape

torch.Size([25])

In [6]:
x[:, 0]

tensor([0.0651, 0.6898, 0.8853, 0.0018, 0.6688, 0.8626, 0.9484, 0.0301, 0.0448,
        0.0907])

In [7]:
x[:, 0].shape

torch.Size([10])

In [8]:
x[2, 0:10]

tensor([0.8853, 0.0131, 0.0110, 0.7991, 0.5143, 0.2523, 0.9144, 0.7662, 0.0627,
        0.3427])

In [9]:
x[2, 0:10].shape

torch.Size([10])

In [11]:
x[0, 0] = 100
x[0, 0]

tensor(100.)

### Fancy Indexing

In [14]:
x = torch.arange(1, 11)
indices = [2, 5, 8]

x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
x[indices]

tensor([3, 6, 9])

In [16]:
x = torch.rand((3, 5))
rows = torch.tensor([1, 0])
cols = torch.tensor([4, 0])

x

tensor([[0.5230, 0.2538, 0.7519, 0.8329, 0.5054],
        [0.6010, 0.8040, 0.5961, 0.3720, 0.1020],
        [0.4283, 0.5220, 0.4046, 0.3958, 0.1404]])

In [17]:
x[rows, cols]

tensor([0.1020, 0.5230])

### More advanced Indexing

In [18]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
x[(x < 2) | (x > 8)]

tensor([0, 1, 9])

In [24]:
x[(x > 2) & (x > 5)]

tensor([6, 7, 8, 9])

In [25]:
x[x.remainder(2) == 0]

tensor([0, 2, 4, 6, 8])

### Useful Operations

In [26]:
torch.where(condition=x > 5, input=x, other=x * 2)

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])

In [27]:
x = torch.tensor([0, 0, 1, 2, 2, 3, 4])
x.unique()

tensor([0, 1, 2, 3, 4])

In [28]:
x.ndimension()

1

In [29]:
x.numel()

7