## Tensors Math & Comparison Operators

In [1]:
import torch
device = 'cuda' if torch.cuda.is_available else 'cpu'

In [2]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8, 7])

x, y

(tensor([1, 2, 3]), tensor([9, 8, 7]))

### Addition

In [3]:
z1 = torch.empty(3)
torch.add(x, y, out=z1)
z1

tensor([10., 10., 10.])

In [4]:
z2 = torch.add(x, y)
z2

tensor([10, 10, 10])

In [5]:
z = x + y
z

tensor([10, 10, 10])

### Subtraction

In [6]:
z = x - y
z

tensor([-8, -6, -4])

### Division

In [7]:
z1 = torch.true_divide(x, y)
z1

tensor([0.1111, 0.2500, 0.4286])

In [8]:
z = x / y
z

tensor([0.1111, 0.2500, 0.4286])

### Inplace Operations

They have a `-` after the function name.

In [9]:
t = torch.zeros(3)
t

tensor([0., 0., 0.])

In [10]:
t.add_(x)

tensor([1., 2., 3.])

In [11]:
t += x
t

tensor([2., 4., 6.])

### Exponentiation

In [12]:
z = x.pow(2)
z

tensor([1, 4, 9])

In [13]:
z = x ** 2
z

tensor([1, 4, 9])

### Simple Comparison

In [14]:
x > 0

tensor([True, True, True])

In [15]:
x < 0

tensor([False, False, False])

### Matrix multiplication

In [16]:
x1 = torch.rand((2, 5))
x2 = torch.rand((5, 3))
x1, x2

(tensor([[0.0071, 0.4598, 0.0033, 0.0134, 0.9158],
         [0.6481, 0.3903, 0.9823, 0.0427, 0.3337]]),
 tensor([[0.4455, 0.1332, 0.7238],
         [0.8788, 0.5986, 0.3967],
         [0.2781, 0.1953, 0.5834],
         [0.3773, 0.9589, 0.7163],
         [0.1584, 0.4769, 0.3951]]))

In [17]:
x3 = torch.mm(x1, x2)
x3

tensor([[0.5583, 0.7265, 0.5610],
        [0.9739, 0.7119, 1.3594]])

In [18]:
x3 = x1.mm(x2)
x3

tensor([[0.5583, 0.7265, 0.5610],
        [0.9739, 0.7119, 1.3594]])

### Matrix Exponentiation

In [19]:
m_exp = torch.rand(5, 5)
m_exp

tensor([[0.1536, 0.2531, 0.0098, 0.3550, 0.2454],
        [0.8834, 0.0564, 0.8133, 0.7150, 0.0882],
        [0.4291, 0.6904, 0.4532, 0.4135, 0.9118],
        [0.6245, 0.7541, 0.4149, 0.6218, 0.5257],
        [0.9355, 0.7753, 0.6896, 0.4696, 0.5594]])

In [20]:
m_exp.matrix_power(3)

tensor([[1.5190, 1.3103, 1.1772, 1.3804, 1.2220],
        [3.7649, 2.8503, 2.9450, 3.0818, 2.4909],
        [4.4562, 3.8282, 3.4659, 3.9687, 3.5788],
        [4.2150, 3.6493, 3.2642, 3.7576, 3.3739],
        [4.7887, 4.0907, 3.7110, 4.1984, 3.7490]])

### Element Wise Multiplication

In [21]:
z = x * y
z

tensor([ 9, 16, 21])

### Dot Product

In [22]:
z = torch.dot(x, y)
z

tensor(46)

### Batch Matrix Multiplication

In [23]:
batch = 32
n = 10
m = 20
p = 30

In [28]:
tens1 = torch.rand((batch, n, m))
tens2 = torch.rand((batch, m, p))
tens1.shape, tens2.shape

(torch.Size([32, 10, 20]), torch.Size([32, 20, 30]))

In [29]:
out_bmm = torch.bmm(tens1, tens2)
out_bmm.shape

torch.Size([32, 10, 30])

### Broadcasting

In [31]:
x1 = torch.rand((5, 5))
x2 = torch.rand((1, 5))
x1, x2

(tensor([[0.8549, 0.9572, 0.6211, 0.2697, 0.5271],
         [0.2095, 0.7500, 0.5859, 0.2184, 0.8027],
         [0.5215, 0.9982, 0.0888, 0.4023, 0.7744],
         [0.0314, 0.4160, 0.0857, 0.4268, 0.6922],
         [0.7030, 0.0953, 0.7012, 0.4880, 0.7941]]),
 tensor([[0.9175, 0.4940, 0.6884, 0.0146, 0.4534]]))

In [32]:
z = x1 - x2  # x1 Automatically expand (Elementwise raised)
z

tensor([[-0.0627,  0.4632, -0.0673,  0.2551,  0.0737],
        [-0.7080,  0.2560, -0.1025,  0.2037,  0.3493],
        [-0.3960,  0.5042, -0.5996,  0.3877,  0.3210],
        [-0.8861, -0.0781, -0.6028,  0.4121,  0.2389],
        [-0.2146, -0.3988,  0.0128,  0.4733,  0.3407]])

In [33]:
z = x1 ** x2  # x1 Automatically expand (Elementwise raised)
z

tensor([[0.8660, 0.9786, 0.7205, 0.9810, 0.7480],
        [0.2383, 0.8675, 0.6921, 0.9780, 0.9052],
        [0.5503, 0.9991, 0.1888, 0.9868, 0.8906],
        [0.0418, 0.6483, 0.1842, 0.9876, 0.8464],
        [0.7237, 0.3130, 0.7832, 0.9896, 0.9008]])

### Other handy operations

In [34]:
sum_x = torch.sum(x, dim=0)
sum_x

tensor(6)

In [36]:
values, indices = torch.max(x, dim=0)
values, indices

(tensor(3), tensor(2))

In [37]:
values, indices = torch.min(x, dim=0)
values, indices

(tensor(1), tensor(0))

In [38]:
torch.abs(x)

tensor([1, 2, 3])

In [39]:
torch.argmax(x, dim=0)

tensor(2)

In [40]:
torch.argmin(x, dim=0)

tensor(0)

In [41]:
torch.mean(x.float(), dim=0)

tensor(2.)

In [42]:
torch.eq(x, y)

tensor([False, False, False])

In [43]:
torch.sort(y, dim=0, descending=False)

torch.return_types.sort(
values=tensor([7, 8, 9]),
indices=tensor([2, 1, 0]))

In [46]:
torch.clamp(x, min=3, max=10)

tensor([3, 3, 3])

In [47]:
x = torch.tensor([1, 0, 1, 1, 1], dtype=torch.bool)
x

tensor([ True, False,  True,  True,  True])

In [49]:
torch.any(x)  # At least one of them is true

tensor(True)

In [51]:
torch.all(x)  # All of them should be true

tensor(False)