## Initializing Tensors

In [1]:
import torch

device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [2]:
my_tensor = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
], dtype=torch.float32, device=device, requires_grad=True)

my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)

In [3]:
my_tensor.dtype

torch.float32

In [4]:
my_tensor.device

device(type='cpu')

In [5]:
my_tensor.shape

torch.Size([2, 3])

In [6]:
my_tensor.requires_grad

True

In [7]:
x = torch.empty(size=(3, 3))
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [8]:
x = torch.zeros((3, 3))
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [10]:
x = torch.ones((3, 3))
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [9]:
x = torch.rand((3, 3))
x

tensor([[0.3696, 0.4404, 0.8466],
        [0.0841, 0.5892, 0.9118],
        [0.0555, 0.6481, 0.7649]])

In [11]:
x = torch.eye(5, 5)
x

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [13]:
x = torch.arange(start=1, end=10, step=2)
x

tensor([1, 3, 5, 7, 9])

In [14]:
x = torch.linspace(start=.1, end=1, steps=10)
x

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [15]:
x = torch.empty((1, 5)).normal_(mean=0., std=1.)
x

tensor([[-1.3542,  1.6404, -1.0561, -1.1689, -0.0222]])

In [16]:
x = torch.empty((1, 5)).uniform_(0., 1.)
x

tensor([[0.4710, 0.2651, 0.4272, 0.4616, 0.3782]])

In [17]:
x = torch.diag(torch.ones(3))
x

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

## Convert Tensors to Different Types

In [20]:
tensor = torch.arange(4)
tensor

tensor([0, 1, 2, 3])

In [21]:
tensor.bool()

tensor([False,  True,  True,  True])

In [22]:
tensor.short()

tensor([0, 1, 2, 3], dtype=torch.int16)

In [23]:
tensor.long()

tensor([0, 1, 2, 3])

In [24]:
tensor.half()

tensor([0., 1., 2., 3.], dtype=torch.float16)

In [25]:
tensor.float()

tensor([0., 1., 2., 3.])

In [26]:
tensor.double()

tensor([0., 1., 2., 3.], dtype=torch.float64)

## Convert Numpy Arrays to Tensors

In [27]:
import numpy as np

In [31]:
np_array = np.ones((5, 5))
np_array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
tensor = torch.from_numpy(np_array)
tensor

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)

In [34]:
np_array_back = tensor.numpy()
np_array_back

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])