## Tensor Reshaping

In [2]:
import torch
device = 'cuda' if torch.cuda.is_available else 'cpu'

In [3]:
x = torch.arange(9)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
x.view((3, 3))

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [5]:
x.reshape((3, 3))

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [6]:
y = x.reshape((3, 3)).t()
y

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])

## Look at the error

In [7]:
y.view(9)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

## For this error we can use `.reshape` simply but we can use this code instead too

In [8]:
y.contiguous().view(9)

tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])

In [9]:
x1 = torch.rand((2, 5))
x2 = torch.rand((2, 5))

torch.cat((x1, x2), dim=0)

tensor([[0.7169, 0.3172, 0.4225, 0.9616, 0.3708],
        [0.8829, 0.1965, 0.2657, 0.6332, 0.5178],
        [0.1920, 0.7993, 0.6825, 0.4819, 0.5769],
        [0.8724, 0.5324, 0.5540, 0.7467, 0.4568]])

In [10]:
torch.cat((x1, x2), dim=0).shape

torch.Size([4, 5])

In [11]:
torch.cat((x1, x2), dim=1).shape

torch.Size([2, 10])

In [13]:
x1.view(-1).shape

torch.Size([10])

In [14]:
batch = 64
x = torch.rand((batch, 2, 5))

z = x.view(batch, -1)
z.shape

torch.Size([64, 10])

In [15]:
z = x.permute(0, 2, 1)
z.shape

torch.Size([64, 5, 2])

In [18]:
x = torch.arange(10)

x.shape

torch.Size([10])

In [19]:
x.unsqueeze(0).shape

torch.Size([1, 10])

In [17]:
x.unsqueeze(1).shape

torch.Size([10, 1])

In [20]:
x = torch.arange(10).unsqueeze(0).unsqueeze(1)
x.shape

torch.Size([1, 1, 10])

In [21]:
z = x.squeeze(1)
z.shape

torch.Size([1, 10])